import { Rect } from "../rect";
import { ScrollView } from "./scroll-view";
import { Layouter } from "../layouters/layouter";
export declare class ListView extends ScrollView {
    itemSpacing: number;
    itemH: number;
    childrenLayouter: Layouter;
    protected beforeDrawChildren(ctx: any): void;
    protected afterDrawChildren(ctx: any): void;
    protected doDrawChildren(ctx: any): void;
    readonly desireHeight: number;
    relayoutChildren(): Rect;
    protected _ih: number;
    protected _is: number;
    constructor(type?: string);
    protected onReset(): void;
    protected static defProps: {} & {
        _x: number;
        _y: number;
        _z: number;
        _w: number;
        _h: number;
        _state: number;
        _value: number;
        _enable: boolean;
        _visible: boolean;
        _selected: boolean;
        _opacity: number;
        _scaleX: number;
        _scaleY: number;
        _pivotX: number;
        _pivotY: number;
        _rotation: number;
        _sensitive: boolean;
        _tips: any;
        _text: any;
        _name: any;
        _hitTestResult: number;
        _isWindow: boolean;
        _mode: number;
        _styleType: any;
        _lp: number;
        _tp: number;
        _rp: number;
        _bp: number;
    } & {
        _ih: number;
        _is: number;
    };
    protected getDefProps(): any;
    static TYPE: string;
    private static recycleBinListView;
    static create(options?: any): ListView;
}
