import { Menu } from "./menu";
import { Style } from "../style";
import { Widget } from "./widget";
import { ImageTile } from "../image-tile";
export declare class MenuBar extends Widget {
    protected _openedMenu: Menu;
    protected _itemWidth: number;
    constructor();
    openedMenu: Menu;
    itemWidth: number;
    onItemEnter(child: MenuBarItem): void;
    addChild(child: Widget, fastMode?: boolean): Widget;
    addSpace(width?: number, position?: number): Widget;
    addLogo(iconURL: any, width?: number): Widget;
    addItem(text: string, onInitSubMenu: Function, width?: number, position?: number): Widget;
    addTextButton(text: string, onClick: Function, width?: number, position?: number): Widget;
    addImageButton(normalIconURL: string, overIconURL: string, activeIconURL: string, disableIconURL: string, checkedIconURL: string, onClick: Function, position?: number): Widget;
    protected onReset(): void;
    protected static defProps: {} & {
        _x: number;
        _y: number;
        _z: number;
        _w: number;
        _h: number;
        _state: number;
        _value: number;
        _enable: boolean;
        _visible: boolean;
        _selected: boolean;
        _opacity: number;
        _scaleX: number;
        _scaleY: number;
        _pivotX: number;
        _pivotY: number;
        _rotation: number;
        _focusable: boolean;
        _sensitive: boolean;
        _tips: any;
        _text: any;
        _name: any;
        _tag: any;
        _hitTestResult: number;
        _isWindow: boolean;
        _mode: number;
        _styleType: any;
        _lp: number;
        _tp: number;
        _rp: number;
        _bp: number;
    } & {
        _itemWidth: number;
    };
    protected getDefProps(): any;
    static TYPE: string;
    private static recycleBin;
    static create(options?: any): MenuBar;
}
export declare class MenuBarItem extends Widget {
    onInitSubMenu: Function;
    protected _normalIcon: ImageTile;
    protected _overIcon: ImageTile;
    protected _activeIcon: ImageTile;
    protected _disableIcon: ImageTile;
    protected _checkedIcon: ImageTile;
    protected _normalIconURL: string;
    protected _overIconURL: string;
    protected _activeIconURL: string;
    protected _disableIconURL: string;
    protected _checkedIconURL: string;
    setIcons(normalIconURL: string, overIconURL?: string, activeIconURL?: string, disableIconURL?: string, checkedIconURL?: string): void;
    protected drawImage(ctx: any, style: Style): Widget;
    reopenMenu(menu: Menu): void;
    protected openMenu(): void;
    protected dispatchClick(evt: any): void;
    constructor();
    dispose(): void;
    protected static defProps: {} & {
        _x: number;
        _y: number;
        _z: number;
        _w: number;
        _h: number;
        _state: number;
        _value: number;
        _enable: boolean;
        _visible: boolean;
        _selected: boolean;
        _opacity: number;
        _scaleX: number;
        _scaleY: number;
        _pivotX: number;
        _pivotY: number;
        _rotation: number;
        _focusable: boolean;
        _sensitive: boolean;
        _tips: any;
        _text: any;
        _name: any;
        _tag: any;
        _hitTestResult: number;
        _isWindow: boolean;
        _mode: number;
        _styleType: any;
        _lp: number;
        _tp: number;
        _rp: number;
        _bp: number;
    } & {
        _normalIconURL: any;
        _overIconURL: any;
        _activeIconURL: any;
        _disableIconURL: any;
        _checkedIconURL: any;
    };
    protected getDefProps(): any;
    static TYPE: string;
    private static recycleBin;
    static create(options?: any): MenuBarItem;
}
