import { Rect } from "../rect";
import { Pages } from "./pages";
import { Widget } from "./widget";
import { TabPage } from "./tab-page";
import { Orientation } from "../consts";
import { TabButtonGroup } from "./tab-button-group";
export declare class TabControl extends Widget {
    protected _pages: Pages;
    protected _orientation: Orientation;
    protected _bgAtTop: boolean;
    protected _bgh: number;
    protected _buttonGroup: TabButtonGroup;
    value: number;
    readonly pages: Pages;
    readonly buttonGroup: TabButtonGroup;
    buttonGroupAtTop: boolean;
    buttonGroupHeight: number;
    removePage(tabPage: TabPage, destroy?: boolean): void;
    addPage(title: string, normalIconURL?: string, currentIconURL?: string, closable?: boolean, closeButtonAtLeft?: boolean): TabPage;
    relayoutChildren(): Rect;
    constructor();
    protected onReset(): void;
    dispose(): void;
    protected static defProps: {} & {
        _x: number;
        _y: number;
        _z: number;
        _w: number;
        _h: number;
        _state: number;
        _value: number;
        _enable: boolean;
        _visible: boolean;
        _selected: boolean;
        _opacity: number;
        _scaleX: number;
        _scaleY: number;
        _pivotX: number;
        _pivotY: number;
        _rotation: number;
        _sensitive: boolean;
        _tips: any;
        _text: any;
        _name: any;
        _hitTestResult: number;
        _isWindow: boolean;
        _mode: number;
        _styleType: any;
        _lp: number;
        _tp: number;
        _rp: number;
        _bp: number;
    } & {
        _bgh: number;
        _bgAtTop: boolean;
    };
    protected getDefProps(): any;
    static TYPE: string;
    private static r;
    static create(options?: any): TabControl;
}
