export declare var locale: string;
export declare var language: string;
export declare var isMacOS: boolean;
export declare var isLinux: boolean;
export declare var isWindows: boolean;
export declare var isAndroid: boolean;
export declare var isIPhone: boolean;
export declare var isIPad: boolean;
export declare var isEdge: boolean;
export declare var isWindowsPhone: boolean;
export declare var isMobile: boolean;
export declare var isPointerSupported: boolean;
export declare var isMSPointerSupported: boolean;
export declare var isTouchSupported: boolean;
export declare function init(_locale: string, userAgent: string): void;
